import * as vscode from 'vscode';

export function getGridCompletions(): vscode.CompletionItem[] {
    const snippetData = [
        ["orientation",            "orientation",                         "Which way the screen is turned."],
        ["orientation_changed",    "orientation_changed",                 "Whether the screen turned this frame."],
        ["orientation_changed?",   "orientation_changed?",                "Check whether the screen turned this frame."],
        ["origin_name",            "origin_name",                         "Which screen corner is used as (0, 0)."],
        ["origin_bottom_left!",    "origin_bottom_left!",                 "Use the bottom-left corner as (0, 0)."],
        ["origin_bottom_left?",    "origin_bottom_left?",                 "Check whether (0, 0) is in the bottom-left corner."],
        ["origin_center!",         "origin_center!",                      "Use the center of the screen as (0, 0)."],
        ["origin_center?",         "origin_center?",                      "Check whether (0, 0) is at the screen center."],
        ["portrait?",              "portrait?",                           "Check whether the screen is taller than it is wide."],
        ["landscape?",             "landscape?",                          "Check whether the screen is wider than it is tall."],
        ["bottom",                 "bottom",                              "Bottom edge of the game screen."],
        ["bottom_px",              "bottom_px",                           "Bottom edge of the game screen. Measured in pixels."],
        ["top",                    "top",                                 "Top edge of the game screen."],
        ["top_px",                 "top_px",                              "Top edge of the game screen. Measured in pixels."],
        ["left",                   "left",                                "Whether the left direction is pressed."],
        ["left_px",                "left_px",                             "Left edge of the game screen. Measured in pixels."],
        ["right",                  "right",                               "Whether the right direction is pressed."],
        ["right_px",               "right_px",                            "Right edge of the game screen. Measured in pixels."],
        ["x",                      "x",                                   "Horizontal screen position."],
        ["x_px",                   "x_px",                                "Horizontal screen position. Measured in pixels."],
        ["y",                      "y",                                   "Vertical screen position."],
        ["y_px",                   "y_px",                                "Vertical screen position. Measured in pixels."],
        ["rect",                   "rect",                                "Position and size of the game screen."],
        ["rect_px",                "rect_px",                             "Screen position and size measured in pixels."],
        ["w",                      "w",                                   "Width of the game screen."],
        ["w_px",                   "w_px",                                "Width of the game screen. Measured in pixels."],
        ["h",                      "h",                                   "Height of the game screen."],
        ["h_px",                   "h_px",                                "Height of the game screen. Measured in pixels."],
        ["center",                 "center",                              "Position of the screen center."],
        ["center_x",               "center_x",                            "Horizontal position of the screen center."],
        ["center_y",               "center_y",                            "Vertical position of the screen center."],
        ["w_half",                 "w_half",                              "Half the width of the game screen."],
        ["h_half",                 "h_half",                              "Half the height of the game screen."],
        ["origin_x",               "origin_x",                            "Horizontal position of the screen origin."],
        ["origin_y",               "origin_y",                            "Vertical position of the screen origin."],
        ["render_origin_x",        "render_origin_x",                     "Horizontal position where drawing begins."],
        ["render_origin_y",        "render_origin_y",                     "Vertical position where drawing begins."],
        ["aspect_ratio_w",         "aspect_ratio_w",                      "Width part of the game screen\u2019s shape ratio."],
        ["aspect_ratio_h",         "aspect_ratio_h",                      "Height part of the game screen\u2019s shape ratio."],
        ["aspect_size",            "aspect_size",                         "Screen size adjusted to fit its shape."],
        ["native_scale",           "native_scale",                        "Scale of the player\u2019s display."],
        ["render_scale",           "render_scale",                        "Scale used to draw game objects on screen."],
        ["texture_scale",          "texture_scale",                       "Scale used for game images."],
        ["texture_scale_enum",     "texture_scale_enum",                  "Image scale setting for the game."],
        ["refresh_rate",           "refresh_rate",                        "How often the display refreshes each second."],
        ["allscreen_rect",         "allscreen_rect",                      "Position and size of the full display area."],
        ["allscreen_rect_px",      "allscreen_rect_px",                   "Full display area measured in pixels."],
        ["allscreen_x",            "allscreen_x",                         "Position or size of the area beyond the game screen."],
        ["allscreen_x_px",         "allscreen_x_px",                      "Allscreen x Measured in pixels."],
        ["allscreen_y",            "allscreen_y",                         "Position or size of the area beyond the game screen."],
        ["allscreen_y_px",         "allscreen_y_px",                      "Allscreen y Measured in pixels."],
        ["allscreen_left",         "allscreen_left",                      "Position or size of the area beyond the game screen."],
        ["allscreen_left_px",      "allscreen_left_px",                   "Allscreen left Measured in pixels."],
        ["allscreen_right",        "allscreen_right",                     "Position or size of the area beyond the game screen."],
        ["allscreen_right_px",     "allscreen_right_px",                  "Allscreen right Measured in pixels."],
        ["allscreen_top",          "allscreen_top",                       "Position or size of the area beyond the game screen."],
        ["allscreen_top_px",       "allscreen_top_px",                    "Allscreen top Measured in pixels."],
        ["allscreen_bottom",       "allscreen_bottom",                    "Position or size of the area beyond the game screen."],
        ["allscreen_bottom_px",    "allscreen_bottom_px",                 "Allscreen bottom Measured in pixels."],
        ["allscreen_w",            "allscreen_w",                         "Position or size of the area beyond the game screen."],
        ["allscreen_w_px",         "allscreen_w_px",                      "Full display width measured in pixels."],
        ["allscreen_w_pt",         "allscreen_w_pt",                      "Full display width measured in screen points."],
        ["allscreen_h",            "allscreen_h",                         "Position or size of the area beyond the game screen."],
        ["allscreen_h_px",         "allscreen_h_px",                      "Full display height measured in pixels."],
        ["allscreen_h_pt",         "allscreen_h_pt",                      "Full display height measured in screen points."],
        ["allscreen_offset",       "allscreen_offset",                    "Space between the game screen and full display area."],
        ["allscreen_offset_px",    "allscreen_offset_px",                 "Space between the game screen and full display, in pixels."],
        ["allscreen_offset_x",     "allscreen_offset_x",                  "Horizontal space outside the game screen."],
        ["allscreen_offset_x_px",  "allscreen_offset_x_px",               "Horizontal space outside the game screen, in pixels."],
        ["allscreen_offset_y",     "allscreen_offset_y",                  "Vertical space outside the game screen."],
        ["allscreen_offset_y_px",  "allscreen_offset_y_px",               "Vertical space outside the game screen, in pixels."],
        ["letterbox?",             "letterbox?",                          "Check whether empty space is added to fit the display."],
        ["letterbox",              "letterbox",                           "Empty space added around the game to fit the display."],
        ["letterbox=",             "letterbox = ${1:VALUE}",              "Set the empty space used to fit the game to the display."],
        ["supported_orientations", "supported_orientations",              "Screen directions allowed by the game settings."],
        ["transform_x",            "transform_x(${1:X})",                 "Convert a game X position to a display position."],
        ["untransform_x",          "untransform_x(${1:X})",               "Convert a display X position back to game coordinates."],
        ["transform_y",            "transform_y(${1:Y})",                 "Convert a game Y position to a display position."],
        ["untransform_y",          "untransform_y(${1:Y})",               "Convert a display Y position back to game coordinates."],
        ["ffi_draw",               "ffi_draw",                            "Low-level drawing access for advanced use."],
        ["set_aspect",             "set_aspect(${1:WIDTH}, ${2:HEIGHT})", "Set the width and height ratio of the game screen."],
        ["hd?",                    "hd?",                                 "Check whether high-definition drawing is enabled."],
        ["hd",                     "hd",                                  "High-definition drawing setting."],
        ["highdpi?",               "highdpi?",                            "Check whether high-density display support is enabled."],
        ["highdpi",                "highdpi",                             "High-density display setting."],
        ["high_dpi_scale",         "high_dpi_scale",                      "Scale used on high-density displays."]
    ];

    const snippets = snippetData.map(([label, snippet, detail]) => {
        const item = new vscode.CompletionItem(label, vscode.CompletionItemKind.Snippet);
        item.insertText = new vscode.SnippetString(snippet);
        item.detail = detail;
        return item;
    });

    return snippets;
}
