import * as vscode from 'vscode';

export function getGtkCompletions(): vscode.CompletionItem[] {
    const snippetData = [
        ["queue_sound",                      "queue_sound '${1:ogg_path}'",                                                         "Play a sound file."],
        ["get_pixels",                       "get_pixels \"${1:PATH}\"",                                                            "Read the pixels from an image file."],
        ["ffi_misc.gtk_dlopen",              "ffi_misc.gtk_dlopen(\"${1:PATH}\")",                                                  "Load a native code library."],
        ["calcstringbox",                    "calcstringbox ${1:TEXT} ${2:SIZE_ENUM} ${3:FONT}",                                    "Measure text width and height; provide text and size."],
        ["request_quit",                     "request_quit",                                                                        "Close the game."],
        ["quit_requested?",                  "quit_requested?",                                                                     "Check whether the game is closing."],
        ["set_window_fullscreen",            "set_window_fullscreen ${1:BOOLEAN}",                                                  "Turn full-screen mode on or off."],
        ["window_fullscreen?",               "window_fullscreen?",                                                                  "Check whether the game fills the screen."],
        ["toggle_window_fullscreen",         "toggle_window_fullscreen",                                                            "Switch between full-screen and windowed mode."],
        ["set_window_scale",                 "set_window_scale ${1:FLOAT}",                                                         "Change how large the game window appears."],
        ["platform?",                        "platform? ${1:SYMBOL}",                                                               "Check whether the game is running on a named platform."],
        ["platform_mappings",                "platform_mappings",                                                                   "Names DragonRuby uses for platforms."],
        ["production?",                      "production?",                                                                         "Check whether the game is in release mode."],
        ["open_uri",                         "open_uri ${1:URI}",                                                                   "Open a web address in the default browser."],
        ["mailto",                           "mailto(${1:EMAIL})",                                                                  "Open an email link in the default mail app."],
        ["dlopen",                           "dlopen(${1:PATH})",                                                                   "Load a native code library."],
        ["get_dlopen_path",                  "get_dlopen_path(${1:NAME})",                                                          "Find where a native code library is stored."],
        ["system",                           "system ${1:STRING}",                                                                  "Run a computer command; its output appears in the console."],
        ["exec",                             "exec ${1:String}",                                                                    "Run a computer command and return its text."],
        ["show_cursor",                      "show_cursor",                                                                         "Show the mouse pointer."],
        ["hide_cursor",                      "hide_cursor",                                                                         "Hide the mouse pointer."],
        ["cursor_shown?",                    "cursor_shown?",                                                                       "Check whether the mouse pointer is visible."],
        ["set_mouse_grab",                   "set_mouse_grab ${1:INTEGER}",                                                         "Choose whether the game captures or hides the mouse."],
        ["set_system_cursor",                "set_system_cursor ${1:STRING}",                                                       "Choose a built-in mouse pointer shape."],
        ["set_cursor",                       "set_cursor ${1:PATH} ${2:X_OFFSET_OPTIONAL} ${3:Y_OFFSET_OPTIONAL)",                  "Use an image as the mouse pointer; optional offsets set its tip."],
        ["create_uuid",                      "create_uuid",                                                                         "Make a unique ID; do not use it for security."],
        ["list_files",                       "list_files ${1:PATH}",                                                                "List files in the game folder."],
        ["stat_file",                        "stat_file ${1:PATH}",                                                                 "Get basic information about a file."],
        ["read_file",                        "read_file ${1:PATH}",                                                                 "Read text from a file in the game folder."],
        ["write_file",                       "write_file ${1:PATH} ${2:STRING}",                                                    "Save text to a file, replacing what is there."],
        ["append_file",                      "append_file ${1:PATH} ${2:STRING}",                                                   "Add text to the end of a file."],
        ["delete_file",                      "delete_file ${1:PATH}",                                                               "Remove a file from the game folder."],
        ["parse_json",                       "parse_json ${1:STRING}",                                                              "Turn JSON text into game data."],
        ["parse_json_file",                  "parse_json_file ${1:PATH}",                                                           "Read a JSON file as game data."],
        ["parse_xml",                        "parse_xml ${1:STRING}",                                                               "Turn XML text into game data."],
        ["parse_xml_file",                   "parse_xml_file ${1:PATH}",                                                            "Read an XML file as game data."],
        ["http_get",                         "http_get ${1:URI}",                                                                   "Request information from a web address."],
        ["http_post",                        "http_post ${1:URI}, ${2:FIELDS_HASH}, ${3:HEADERS}",                                  "Send data to a web address."],
        ["http_post_body",                   "http_post_body ${1:URI}, ${2:STRING}, ${3:HEADERS}",                                  "Send text to a web address."],
        ["http_head",                        "http_head ${1:URI}, ${2:HEADERS}",                                                    "Ask a web address for its headers."],
        ["http_put",                         "http_put ${1:URI}, ${2:FIELDS_HASH}, ${3:HEADERS}",                                   "Send updated data to a web address."],
        ["start_server!",                    "start_server! port: ${1:9001}, enable_in_prod: ${2:false}",                           "Start a web server for the game."],
        ["request.respond",                  "respond ${1:HTTP_CODE}, ${2:HTTP_RESPONSE}",                                          "Send a status and response to a web request."],
        ["http_respond",                     "http_respond(${1:REQUEST}, ${2:STATUS}, ${3:BODY})",                                  "Reply to a web request with a status and message."],
        ["http_response_data",               "http_response_data(${1:RESPONSE})",                                                   "Get the data returned by a web request."],
        ["http_response_header",             "http_response_header(${1:RESPONSE}, ${2:NAME})",                                      "Get one header from a web response."],
        ["version",                          "version",                                                                             "DragonRuby version used by the game."],
        ["version_pro?",                     "version_pro?",                                                                        "Check whether this is the Pro edition."],
        ["game_version",                     "game_version",                                                                        "Version set for this game."],
        ["reset",                            "reset seed: ${1:OPTIONAL}",                                                           "Restart game state; an optional seed repeats random results."],
        ["seed",                             "seed",                                                                                "Current starting point for random numbers."],
        ["started_at",                       "started_at",                                                                          "When this game session began."],
        ["reset_next_tick",                  "reset_next_tick",                                                                     "Restart the game on the next frame."],
        ["reset_sprite",                     "reset_sprite ${1:PATH}",                                                              "Reload an image or render target."],
        ["reset_sprites",                    "reset_sprites ${1:DIRECTORY_OPTIONAL}",                                               "Reload all images and render targets, optionally from one folder."],
        ["calcspritebox",                    "calcspritebox ${1:PATH}",                                                             "Get an image\u2019s width and height."],
        ["current_framerate",                "current_framerate",                                                                   "Current frames drawn per second."],
        ["framerate_diagnostics_primitives", "framerate_diagnostics_primitives",                                                    "Draw information to help check game speed."],
        ["warn_array_primitives!",           "warn_array_primitives!",                                                              "Show warnings for older shape formats."],
        ["benchmark",                        "benchmark ${1:iterations/seconds}: ${2:LAMBDAS}",                                     "Compare how long a group of code blocks takes."],
        ["notify!",                          "notify! \"${1:STRING}\", ${2:INTEGER_FRAME_DURATION_OPTIONAL}",                       "Show a short message while testing the game."],
        ["notify_extended!",                 "notify_extended! message: \"${1:STRING}\", duration: ${2:INTEGER}, env: ${3:SYMBOL}", "Show a message with display options."],
        ["slowmo!",                          "slowmo! ${1:INTEGER}",                                                                "Slow down the game to watch what happens."],
        ["show_console",                     "show_console",                                                                        "Show the developer console."],
        ["hide_console",                     "hide_console",                                                                        "Hide the developer console."],
        ["enable_console",                   "enable_console",                                                                      "Allow the developer console to open."],
        ["disable_console",                  "disable_console",                                                                     "Prevent the developer console from opening."],
        ["disable_reset_via_ctrl_r",         "disable_reset_via_ctrl_r",                                                            "Stop Ctrl+R from restarting the game."],
        ["disable_controller_config",        "disable_controller_config",                                                           "Hide controller setup."],
        ["enable_controller_config",         "enable_controller_config",                                                            "Show controller setup."],
        ["start_recording",                  "start_recording ${1:SEED_OPTIONAL}",                                                  "Start recording player input, optionally using a chosen random seed."],
        ["stop_recording",                   "stop_recording ${1:PATH}",                                                            "Finish recording and save player input to a file."],
        ["cancel_recording",                 "cancel_recording",                                                                    "Discard the current input recording."],
        ["start_replay",                     "start_replay ${1:PATH}",                                                              "Replay player input saved in a file."],
        ["stop_replay",                      "stop_replay",                                                                         "Stop replaying recorded input."],
        ["get_base_dir",                     "get_base_dir",                                                                        "Get the folder DragonRuby is running from."],
        ["get_game_dir",                     "get_game_dir",                                                                        "Get the game\u2019s folder."],
        ["get_game_dir_url",                 "get_game_dir_url",                                                                    "Get a link to the game folder."],
        ["open_game_dir",                    "open_game_dir",                                                                       "Open the game folder."],
        ["write_file_root",                  "write_file_root ${1:PATH}, ${2:TEXT}",                                                "Save text in DragonRuby\u2019s shared folder."],
        ["append_file_root",                 "append_file_root ${1:PATH}, ${2:TEXT}",                                               "Add text to a file in DragonRuby\u2019s shared folder."],
        ["argv",                             "argv",                                                                                "Text used to start the game."],
        ["cli_arguments",                    "cli_arguments",                                                                       "Options passed when starting the game."],
        ["download_stb_rb",                  "download_stb_rb \"${1:STRING}\", \"${2:STRING_OPTIONAL}\", \"${3:STRING_OPTIONAL}\"", "Download the standard library."],
        ["download_stb_rb_raw",              "download_stb_rb_raw \"${1:STRING}\", \"${2:PATH}\"",                                  "Download a standard library file."],
        ["download_lib",                     "download_lib(${1:NAME})",                                                             "Download a DragonRuby library."],
        ["download_lib_raw",                 "download_lib_raw(${1:URI}, ${2:PATH})",                                               "Download a library file from a web address."],
        ["reload_history",                   "reload_history",                                                                      "Recent file reload information."],
        ["reload_history_pending",           "reload_history_pending",                                                              "Files waiting to reload."],
        ["reload_if_needed",                 "reload_if_needed ${1:PATH}, ${2:FORCE_BOOLEAN_OPTIONAL}",                             "Reload a changed file; optional flag forces a reload."],
        ["add_caller_to_puts!",              "add_caller_to_puts!",                                                                 "Include the calling file in console messages."],
        ["can_resize_window?",               "can_resize_window?",                                                                  "Check whether the game window can be resized."],
        ["set_window_size",                  "set_window_size(${1:WIDTH}, ${2:HEIGHT})",                                            "Set the game window width and height."],
        ["set_window_position",              "set_window_position(${1:X}, ${2:Y})",                                                 "Move the game window to a screen position."],
        ["set_window_title",                 "set_window_title(${1:TITLE})",                                                        "Set the title shown on the game window."],
        ["can_close_window?",                "can_close_window?",                                                                   "Check whether the game window can be closed."],
        ["move_window_to_next_display",      "move_window_to_next_display",                                                         "Move the game window to another display."],
        ["maximize_window",                  "maximize_window",                                                                     "Make the game window as large as possible."],
        ["can_change_orientation?",          "can_change_orientation?",                                                             "Check whether the screen can be turned."],
        ["toggle_orientation",               "toggle_orientation",                                                                  "Switch the screen between portrait and landscape."],
        ["set_orientation",                  "set_orientation(${1:ORIENTATION})",                                                   "Set the screen direction."],
        ["set_hd_max_scale",                 "set_hd_max_scale(${1:SCALE})",                                                        "Limit how large high-definition mode can draw."],
        ["toggle_hd_letterbox",              "toggle_hd_letterbox",                                                                 "Switch display-fitting borders on or off."],
        ["set_hd_letterbox",                 "set_hd_letterbox(${1:ENABLED})",                                                      "Choose whether to add borders to fit the display."],
        ["raise_window",                     "raise_window",                                                                        "Bring the game window in front of other windows."],
        ["on_tick_count",                    "on_tick_count(${1:TICK_COUNT}) { $0 }",                                               "Run code when the game reaches a frame number."],
        ["calcstringbox_h",                  "calcstringbox_h(${1:TEXT}, ${2:SIZE})",                                               "Measure how tall text will be."],
        ["get_string_rect",                  "get_string_rect(${1:TEXT})",                                                          "Get the area covered by text."],
        ["openurl",                          "openurl(${1:URL})",                                                                   "Open a web address in the default browser."],
        ["getenv",                           "getenv(${1:NAME})",                                                                   "Read a setting from the computer environment."],
        ["setenv",                           "setenv(${1:NAME}, ${2:VALUE})",                                                       "Set a setting for the computer environment."],
        ["read_save_data",                   "read_save_data(${1:PATH})",                                                           "Load data saved by the game."],
        ["write_save_data",                  "write_save_data(${1:PATH}, ${2:DATA})",                                               "Save data for the next game session."],
        ["reset_and_replay",                 "reset_and_replay ${1:FILE_OPTIONAL}, speed: ${2:1}",                                  "Restart, then replay recorded input."],
        ["reboot",                           "reboot",                                                                              "Restart the game and reload its files."],
        ["get_sprite_rect",                  "get_sprite_rect(${1:PATH})",                                                          "Get an image\u2019s width and height."],
        ["trace_puts!",                      "trace_puts!(${1:MESSAGE})",                                                           "Write a message to the trace log."],
        ["current_thermal_state",            "current_thermal_state",                                                               "Current device temperature status."]
    ];

    const snippets = snippetData.map(([label, snippet, detail]) => {
        const item = new vscode.CompletionItem(label, vscode.CompletionItemKind.Snippet);
        item.insertText = new vscode.SnippetString(snippet);
        item.detail = detail;
        return item;
    });

    return snippets;
}
