import * as vscode from 'vscode';

export function getControllerOneCompletions(): vscode.CompletionItem[] {
    const snippetData = [
        ["name",                                     "name",                                                                              "Name of this game controller."],
        ["active",                                   "active",                                                                            "Whether this controller was used recently."],
        ["connected",                                "connected",                                                                         "Whether this controller is connected."],
        ["up",                                       "up",                                                                                "Whether the up direction is pressed."],
        ["down",                                     "down",                                                                              "Whether the down direction is pressed."],
        ["left",                                     "left",                                                                              "Whether the left direction is pressed."],
        ["right",                                    "right",                                                                             "Whether the right direction is pressed."],
        ["up_dpad",                                  "up_dpad",                                                                           "Whether up is pressed on the directional pad."],
        ["down_dpad",                                "down_dpad",                                                                         "Whether down is pressed on the directional pad."],
        ["left_dpad",                                "left_dpad",                                                                         "Whether left is pressed on the directional pad."],
        ["right_dpad",                               "right_dpad",                                                                        "Whether right is pressed on the directional pad."],
        ["left_right",                               "left_right",                                                                        "Horizontal movement: -1 left, 0 still, or 1 right."],
        ["up_down",                                  "up_down",                                                                           "Vertical movement: -1 down, 0 still, or 1 up."],
        ["last_left_right",                          "last_left_right",                                                                   "Horizontal direction used most recently."],
        ["last_up_down",                             "last_up_down",                                                                      "Vertical direction used most recently."],
        ["directional_vector",                       "directional_vector",                                                                "Current movement direction from the keyboard or controller."],
        ["directional_vector_left",                  "directional_vector_left",                                                           "Movement direction from the left stick."],
        ["directional_vector_right",                 "directional_vector_right",                                                          "Current movement direction from the right stick."],
        ["directional_vector_dpad",                  "directional_vector_dpad",                                                           "Movement direction from the directional pad."],
        ["directional_vector_left_analog",           "directional_vector_left_analog",                                                    "Movement direction from the left stick."],
        ["directional_vector_right_analog",          "directional_vector_right_analog",                                                   "Movement direction from the right stick."],
        ["directional_vector_left_analog_cardinal",  "directional_vector_left_analog_cardinal",                                           "Nearest up, down, left, or right direction from the left stick."],
        ["directional_vector_right_analog_cardinal", "directional_vector_right_analog_cardinal",                                          "Nearest up, down, left, or right direction from the right stick."],
        ["directional_vector_buttons",               "directional_vector_buttons",                                                        "Movement direction from the controller buttons."],
        ["directional_angle",                        "directional_angle",                                                                 "Angle of the current movement direction."],
        ["left_analog_x_raw",                        "left_analog_x_raw",                                                                 "Horizontal position of the left stick."],
        ["right_analog_x_raw",                       "right_analog_x_raw",                                                                "Horizontal position of the right stick."],
        ["left_analog_y_raw",                        "left_analog_y_raw",                                                                 "Vertical position of the left stick."],
        ["right_analog_y_raw",                       "right_analog_y_raw",                                                                "Vertical position of the right stick."],
        ["left_analog_x_perc",                       "left_analog_x_perc",                                                                "Horizontal left-stick position, from -1 to 1."],
        ["right_analog_x_perc",                      "right_analog_x_perc",                                                               "Horizontal right-stick position, from -1 to 1."],
        ["left_analog_y_perc",                       "left_analog_y_perc",                                                                "Vertical left-stick position, from -1 to 1."],
        ["right_analog_y_perc",                      "right_analog_y_perc",                                                               "Vertical right-stick position, from -1 to 1."],
        ["dpad_up",                                  "dpad_up",                                                                           "Whether up is pressed on the directional pad."],
        ["directional_up",                           "directional_up",                                                                    "Whether up is pressed on the directional pad."],
        ["dpad_down",                                "dpad_down",                                                                         "Whether down is pressed on the directional pad."],
        ["directional_down",                         "directional_down",                                                                  "Whether down is pressed on the directional pad."],
        ["dpad_left",                                "dpad_left",                                                                         "Whether left is pressed on the directional pad."],
        ["directional_left",                         "directional_left",                                                                  "Whether left is pressed on the directional pad."],
        ["dpad_right",                               "dpad_right",                                                                        "Whether right is pressed on the directional pad."],
        ["directional_right",                        "directional_right",                                                                 "Whether right is pressed on the directional pad."],
        ["a",                                        "a",                                                                                 "Whether the A controller button is pressed."],
        ["b",                                        "b",                                                                                 "Whether the B controller button is pressed."],
        ["x",                                        "x",                                                                                 "Whether the X controller button is pressed."],
        ["y",                                        "y",                                                                                 "Whether the Y controller button is pressed."],
        ["l1",                                       "l1",                                                                                "Whether the L1 controller button is pressed."],
        ["r1",                                       "r1",                                                                                "Whether the R1 controller button is pressed."],
        ["l2",                                       "l2",                                                                                "Whether the L2 controller button is pressed."],
        ["r2",                                       "r2",                                                                                "Whether the R2 controller button is pressed."],
        ["l3",                                       "l3",                                                                                "Whether the L3 controller button is pressed."],
        ["r3",                                       "r3",                                                                                "Whether the R3 controller button is pressed."],
        ["start",                                    "start",                                                                             "Whether the START controller button is pressed."],
        ["select",                                   "select",                                                                            "Whether the SELECT controller button is pressed."],
        ["truthy_keys",                              "truthy_keys",                                                                       "Controller buttons pressed right now."],
        ["key_down",                                 "key_down.${1:BUTTON}",                                                              "Keys pressed this frame."],
        ["key_held",                                 "key_held.${1:BUTTON}",                                                              "Keys that are currently held."],
        ["key_up",                                   "key_up.${1:BUTTON}",                                                                "Keys released this frame."],
        ["left_analog_active?",                      "left_analog_active?(threshold_raw: ${1:optional}, threshold_perc: ${2:optional})",  "Check whether a stick is past a movement threshold."],
        ["right_analog_active?",                     "right_analog_active?(threshold_raw: ${1:optional}, threshold_perc: ${2:optional})", "Check whether a stick is past a movement threshold."],
        ["left_analog_angle",                        "left_analog_angle",                                                                 "Angle of the stick\u2019s current direction."],
        ["right_analog_angle",                       "right_analog_angle",                                                                "Angle of the stick\u2019s current direction."],
        ["analog_dead_zone",                         "analog_dead_zone",                                                                  "How far a stick can move before input is counted."],
        ["left_hand",                                "left_hand",                                                                         "Position and direction of the controller hand."],
        ["right_hand",                               "right_hand",                                                                        "Position and direction of the controller hand."],
        ["accept",                                   "accept",                                                                            "Whether the controller\u2019s accept button was pressed."],
        ["cancel",                                   "cancel",                                                                            "Whether the controller\u2019s cancel button was pressed."],
        ["key_down?",                                "key_down?(${1:BUTTON})",                                                            "Check whether a button was pressed this frame."],
        ["key_held?",                                "key_held?(${1:BUTTON})",                                                            "Check whether a button is still held."],
        ["key_up?",                                  "key_up?(${1:BUTTON})",                                                              "Check whether a button was released this frame."],
    ];

    const snippets = snippetData.map(([label, snippet, detail]) => {
        const item = new vscode.CompletionItem(label, vscode.CompletionItemKind.Snippet);
        item.insertText = new vscode.SnippetString(snippet);
        item.detail = detail;
        return item;
    });

    return snippets;
}
